# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telemetry.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 240)
        Dialog.setMinimumSize(QtCore.QSize(550, 240))
        Dialog.setMaximumSize(QtCore.QSize(550, 240))
        self.copter_text = QtWidgets.QLabel(Dialog)
        self.copter_text.setGeometry(QtCore.QRect(80, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.copter_text.setFont(font)
        self.copter_text.setAlignment(QtCore.Qt.AlignCenter)
        self.copter_text.setObjectName("copter_text")
        self.go_pushButton = QtWidgets.QPushButton(Dialog)
        self.go_pushButton.setGeometry(QtCore.QRect(10, 10, 93, 41))
        self.go_pushButton.setObjectName("go_pushButton")
        self.number_spinBox = QtWidgets.QSpinBox(Dialog)
        self.number_spinBox.setGeometry(QtCore.QRect(160, 20, 42, 22))
        self.number_spinBox.setObjectName("number_spinBox")
        self.x_1 = QtWidgets.QLabel(Dialog)
        self.x_1.setGeometry(QtCore.QRect(10, 100, 21, 16))
        self.x_1.setAlignment(QtCore.Qt.AlignCenter)
        self.x_1.setObjectName("x_1")
        self.y_1 = QtWidgets.QLabel(Dialog)
        self.y_1.setGeometry(QtCore.QRect(10, 150, 21, 16))
        self.y_1.setAlignment(QtCore.Qt.AlignCenter)
        self.y_1.setObjectName("y_1")
        self.z_1 = QtWidgets.QLabel(Dialog)
        self.z_1.setGeometry(QtCore.QRect(10, 200, 21, 16))
        self.z_1.setAlignment(QtCore.Qt.AlignCenter)
        self.z_1.setObjectName("z_1")
        self.z_2 = QtWidgets.QLabel(Dialog)
        self.z_2.setGeometry(QtCore.QRect(40, 200, 51, 16))
        self.z_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.z_2.setObjectName("z_2")
        self.x_2 = QtWidgets.QLabel(Dialog)
        self.x_2.setGeometry(QtCore.QRect(40, 100, 51, 16))
        self.x_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.x_2.setObjectName("x_2")
        self.y_2 = QtWidgets.QLabel(Dialog)
        self.y_2.setGeometry(QtCore.QRect(40, 150, 51, 16))
        self.y_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.y_2.setObjectName("y_2")
        self.mode_2 = QtWidgets.QLabel(Dialog)
        self.mode_2.setGeometry(QtCore.QRect(470, 130, 71, 16))
        self.mode_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mode_2.setObjectName("mode_2")
        self.armed_2 = QtWidgets.QLabel(Dialog)
        self.armed_2.setGeometry(QtCore.QRect(470, 100, 71, 16))
        self.armed_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.armed_2.setObjectName("armed_2")
        self.frame_id_1 = QtWidgets.QLabel(Dialog)
        self.frame_id_1.setGeometry(QtCore.QRect(400, 170, 61, 16))
        self.frame_id_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_id_1.setObjectName("frame_id_1")
        self.armed_1 = QtWidgets.QLabel(Dialog)
        self.armed_1.setGeometry(QtCore.QRect(400, 100, 51, 16))
        self.armed_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.armed_1.setObjectName("armed_1")
        self.frame_id_2 = QtWidgets.QLabel(Dialog)
        self.frame_id_2.setGeometry(QtCore.QRect(470, 170, 71, 16))
        self.frame_id_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_id_2.setObjectName("frame_id_2")
        self.mode_1 = QtWidgets.QLabel(Dialog)
        self.mode_1.setGeometry(QtCore.QRect(400, 130, 51, 16))
        self.mode_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mode_1.setObjectName("mode_1")
        self.voltage_2 = QtWidgets.QLabel(Dialog)
        self.voltage_2.setGeometry(QtCore.QRect(470, 200, 71, 16))
        self.voltage_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voltage_2.setObjectName("voltage_2")
        self.voltage_1 = QtWidgets.QLabel(Dialog)
        self.voltage_1.setGeometry(QtCore.QRect(400, 200, 51, 16))
        self.voltage_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.voltage_1.setObjectName("voltage_1")
        self.roll_2 = QtWidgets.QLabel(Dialog)
        self.roll_2.setGeometry(QtCore.QRect(190, 200, 61, 16))
        self.roll_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.roll_2.setObjectName("roll_2")
        self.yaw_1 = QtWidgets.QLabel(Dialog)
        self.yaw_1.setGeometry(QtCore.QRect(140, 100, 31, 16))
        self.yaw_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yaw_1.setObjectName("yaw_1")
        self.pitch_1 = QtWidgets.QLabel(Dialog)
        self.pitch_1.setGeometry(QtCore.QRect(140, 150, 41, 16))
        self.pitch_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pitch_1.setObjectName("pitch_1")
        self.roll_1 = QtWidgets.QLabel(Dialog)
        self.roll_1.setGeometry(QtCore.QRect(140, 200, 31, 16))
        self.roll_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.roll_1.setObjectName("roll_1")
        self.pitch_2 = QtWidgets.QLabel(Dialog)
        self.pitch_2.setGeometry(QtCore.QRect(190, 150, 61, 16))
        self.pitch_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pitch_2.setObjectName("pitch_2")
        self.yaw2 = QtWidgets.QLabel(Dialog)
        self.yaw2.setGeometry(QtCore.QRect(190, 100, 61, 16))
        self.yaw2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yaw2.setObjectName("yaw2")
        self.vy_1 = QtWidgets.QLabel(Dialog)
        self.vy_1.setGeometry(QtCore.QRect(270, 150, 31, 16))
        self.vy_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vy_1.setObjectName("vy_1")
        self.vx_2 = QtWidgets.QLabel(Dialog)
        self.vx_2.setGeometry(QtCore.QRect(320, 100, 61, 16))
        self.vx_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vx_2.setObjectName("vx_2")
        self.vz_1 = QtWidgets.QLabel(Dialog)
        self.vz_1.setGeometry(QtCore.QRect(270, 200, 31, 16))
        self.vz_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vz_1.setObjectName("vz_1")
        self.vy_2 = QtWidgets.QLabel(Dialog)
        self.vy_2.setGeometry(QtCore.QRect(320, 150, 61, 16))
        self.vy_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vy_2.setObjectName("vy_2")
        self.vz_2 = QtWidgets.QLabel(Dialog)
        self.vz_2.setGeometry(QtCore.QRect(320, 200, 61, 16))
        self.vz_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vz_2.setObjectName("vz_2")
        self.vx_1 = QtWidgets.QLabel(Dialog)
        self.vx_1.setGeometry(QtCore.QRect(270, 100, 31, 16))
        self.vx_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vx_1.setObjectName("vx_1")
        self.back = QtWidgets.QLabel(Dialog)
        self.back.setGeometry(QtCore.QRect(0, 0, 551, 241))
        self.back.setObjectName("back")
        self.back.raise_()
        self.copter_text.raise_()
        self.go_pushButton.raise_()
        self.number_spinBox.raise_()
        self.x_1.raise_()
        self.y_1.raise_()
        self.z_1.raise_()
        self.z_2.raise_()
        self.x_2.raise_()
        self.y_2.raise_()
        self.mode_2.raise_()
        self.armed_2.raise_()
        self.frame_id_1.raise_()
        self.armed_1.raise_()
        self.frame_id_2.raise_()
        self.mode_1.raise_()
        self.voltage_2.raise_()
        self.voltage_1.raise_()
        self.roll_2.raise_()
        self.yaw_1.raise_()
        self.pitch_1.raise_()
        self.roll_1.raise_()
        self.pitch_2.raise_()
        self.yaw2.raise_()
        self.vy_1.raise_()
        self.vx_2.raise_()
        self.vz_1.raise_()
        self.vy_2.raise_()
        self.vz_2.raise_()
        self.vx_1.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Telemetry"))
        self.copter_text.setText(_translate("Dialog", "Copter"))
        self.go_pushButton.setText(_translate("Dialog", "Go"))
        self.x_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">x=</span></p></body></html>"))
        self.y_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">y=</span></p></body></html>"))
        self.z_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">z=</span></p></body></html>"))
        self.z_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.x_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.y_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.mode_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">MANUALE</span></p></body></html>"))
        self.armed_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">False</span></p></body></html>"))
        self.frame_id_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">farme id=</span><br/></p></body></html>"))
        self.armed_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">armed=</span></p></body></html>"))
        self.frame_id_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">aruco_map</span></p></body></html>"))
        self.mode_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">mode=</span></p></body></html>"))
        self.voltage_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.voltage_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">voltage=</span></p></body></html>"))
        self.roll_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.yaw_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">yaw=</span></p></body></html>"))
        self.pitch_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">pitch=</span></p></body></html>"))
        self.roll_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">roll=</span></p></body></html>"))
        self.pitch_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.yaw2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.vy_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">vy=</span></p></body></html>"))
        self.vx_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.vz_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">vz=</span></p></body></html>"))
        self.vy_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.vz_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">0.000</span></p></body></html>"))
        self.vx_1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#c8c8c8;\">vx=</span></p></body></html>"))
        self.back.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/telem/telem_bakground.png\"/></p></body></html>"))

import telem_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

